using System.Collections;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserManagementAPI.Models.ViewModels;

namespace UserManagementAPI.Controllers
{
    [Route("api/[controller]/users")]
    [ApiController]
    public class MetricsController : ControllerBase
    {
        private readonly SqlDbContext _context;

        public MetricsController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: api/Metrics
        
        /// <summary>
        /// Get the number of users, tickets and bookings(userTickets)
        /// </summary>
        /// <returns> Total number of Users, Tickets, Bookings(userTickets)</returns>
        /// <example>
        /// {
        /// "users": 123,
        /// "tickets": 456,
        /// "bookings": 789
        /// }
        /// </example>
        [HttpGet]
        public IActionResult GetMetrics()
        {
            var users =  _context.Users.Count();
            var tickets = _context.Tickets.Count();
            var bookings = _context.UserTickets.Count();
            return Ok(new {users, tickets, bookings});
        }
        /// <summary>
        /// Gets the number of users by age range (0-100)
        /// </summary>
        /// <returns>
        /// A list of age ranges and the number of users in each range
        /// </returns>
        ///  <example>
        ///  [{"ageSpan": "0-20", "quantity": 123}, {"ageSpan": "21-30", "quantity": 456}, ...]
        ///  </example>
        [HttpGet]
        [Route("age")]

        public async Task<ActionResult<IEnumerable<UserAgeViewModel>>> GetUsersByAge()
        {
            var users = await _context.Users.Include(x => x.UserInfo).ToListAsync();

            
            var ageRanges = new List<(int Min, int Max, string Label)>
            {
                (0, 20, "0-20"),
                (21, 30, "21-30"),
                (31, 40, "31-40"),
                (41, 50, "41-50"),
                (51, 60, "51-60"),
                (61, 70, "61-70"),
                (71, 80, "71-80"),
                (81, 90, "81-90"),
                (91, 100, "91-100")
               
            };

          
            var groupedUsers = ageRanges
                .Select(range => new UserAgeViewModel
                {
                    AgeSpan = range.Label,
                    Quantity = users.Count(user => user.UserInfo?.Age >= range.Min && user.UserInfo?.Age <= range.Max)
                })
                .Where(group => group.Quantity > 0)
                .ToList();

            return groupedUsers;
        }

        /// <summary>
        ///  Gets the number of users by country
        /// </summary>
        /// <returns>
        ///  A list of countries and the number of users in each country
        /// </returns>
        /// <example>
        ///  [{"country": "United States", "quantity": 123}, {"country": "United Kingdom", "quantity": 456}, ...]
        /// </example>
        [HttpGet]
        [Route("Country")]
        public async Task<ActionResult<IEnumerable<UserCountryViewModel>>> GetUsersByCountry()
        {
            var users = await _context.Users.Include(x => x.Location).ToListAsync();
            
            var groupedUsers = users
                .GroupBy(user => user.Location?.Country)
                .Select(group => new UserCountryViewModel
                {
                    Country = group.Key,
                    Quantity = group.Count()
                })
                .Where(group => group.Quantity > 0)
                .ToList();
            return groupedUsers;
        }
        /// <summary>
        ///  Gets the number of users by gender 
        /// </summary>
        /// <returns>
        ///  A list of genders and the number of users with each gender
        /// </returns>
        /// <example>
        /// [{"gender": "Male", "quantity": 23}, {"gender": "Female", "quantity": 15}, ...]
        /// </example>
        [HttpGet]
        [Route("Gender")]

        public async Task<ActionResult<IEnumerable<UserGenderViewModel>>> GetUsersByGender()
        {
            var users = await _context.Users.Include(x => x.UserInfo).ToListAsync();

            var groupedUsers = users.GroupBy(user => user.UserInfo?.Gender)
                .Select(group => new UserGenderViewModel
                {
                    Gender = group.Key,
                    Quantity = group.Count()
                })
                .Where(group => group.Quantity > 0)
                .ToList();
            return groupedUsers;

        }
        /// <summary>
        ///  Gets the revenue per ticket
        /// </summary>
        /// <returns>
        ///  A list of tickets and the revenue generated by each ticket
        /// </returns>
        /// <example>
        ///[{"ticketName": "General", "revenue": 123}, {"ticketName": "VIP", "revenue": 456}, ...]
        /// </example>
         
        [HttpGet]
        [Route("Revenue/PerTicket")]
        public async Task<ActionResult<IEnumerable<TicketsRevenueViewModel>>> GetRevenuePerTicket()
        {
            var tickets = await _context.UserTickets.Include(x=> x.Ticket).ToListAsync();

            var groupedTickets = tickets.GroupBy(ticket => ticket.Ticket.TicketName)
                .Select(group => new TicketsRevenueViewModel
                {
                    TicketName = group.Key,
                    Revenue = group.Sum(ticket => ticket.Ticket.Price)
                })
                .Where(group => group.Revenue > 0)
                .ToList();
            return groupedTickets;
        }
        /// <summary>
        ///  Gets the revenue per user
        /// </summary>
        /// <returns>
        /// A list of users and the revenue generated by each user
        /// </returns>
        /// <example>
        /// [{"email": "user1@example", "revenue": 123}, {"email": "user2@example", "revenue": 456}, ...]
        /// </example>
        [HttpGet]
        [Route("Revenue/PerUser")]

        public async Task<ActionResult<IEnumerable<UserRevenueViewModel>>> GetRevenuePerUser()
        {
            var users = await _context.UserTickets.Include(x => x.User).Include(y=> y.Ticket).ToListAsync();
            var groupedUsers = users.GroupBy(user => user.User.Email)
                .Select(group => new UserRevenueViewModel
                {
                    Email = group.Key,
                    Revenue = group.Sum(user => user.Ticket.Price)
                })
                .Where(group => group.Revenue > 0)
                .ToList();
            return groupedUsers;
        }

        /// <summary>
        ///  Gets the total revenue from all tickets
        /// </summary>
        /// <returns>
        ///  int representing the total revenue
        /// </returns>
        /// <example>
        ///   123
        /// </example>

        [HttpGet]
        [Route("Revenue/Total")]
        public async Task<IActionResult> GetTotalRevenue()
        {
            var tickets = await _context.UserTickets.Include(x => x.Ticket).ToListAsync();
            var totalRevenue = tickets.Sum(ticket => ticket.Ticket.Price);
            return Ok(new {totalRevenue});
        }


    }

    
}
